# Generated by Django 5.1.3 on 2024-11-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalproperty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('offset', models.BigIntegerField(default=0)),
                ('total_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='property_media', to='rentalproperty.chunkedupload'),
        ),
    ]
