# Generated by Django 5.1.3 on 2024-11-27 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalproperty', '0003_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
