# Generated by Django 5.1.3 on 2024-11-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
